### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by ream88** [lightningtgc/MProgress.js#1]

**Comment by goldensunliu** [comment]
I filed the same issue #4, sorry about that. It seems like one of the owner have replied to that issue

**Comment by lightningtgc** [comment]
Thanks @haihappen .
I will I will register it today. (:

**Comment by lightningtgc** [comment]
Hi, @haihappen and @goldensunliu ,

I have registered mprogress at bower.

So you can install Mprogress.js by using:

```
bower install mprogress
```

Thanks.

**Comment by ream88** [comment]
Thank you! 😊
